import json

with open('3d_panels/petes_dragon_specs.json') as f:
    specs = json.load(f)

contour_pts = specs['contour_pts']
ordered_leds = specs['ordered_leds']
led_rotations_deg = specs['led_rotations_deg']
number_positions = specs['number_positions']
fastener_tabs = specs['fastener_tabs']

scad_code = f'''// ============================================================================
// 🏰 Main Street Electrical Parade (WDW 10K) - Flexible TPU Chest Armor Tray
// Character: Pete's Dragon (Elliott) - 100 Addressable Fairy Light Bulbs
// Sized for Snapmaker U1 | Material: 95A TPU | Fasteners: Backside Rim Eyelets
// Hardware Architecture: 6.0mm Open Chassis Tray (2mm Front Plate + 4mm Perimeter Rim)
// Cross Section:
//   - General Tray Floor: 2.0mm
//   - LED Pocket Floor: 1.0mm (1.0mm interior pocket recess)
//   - LED Socket Collars: 3.0mm tall (Z = 1.0 to 4.0mm)
//   - Clearance when laying front-side up: 2.0mm space under collars to table (Z = 4.0 to 6.0mm)
//   - Perimeter Rim: 4.0mm tall (Z = 2.0 to 6.0mm)
// 10mm x 5mm Rotated Oval Collars (3mm Tall) with 4mm Wire Notches
// 2mm x 2mm Square Optical Windows | Etched Numbers 1-100 on Inner Floor
// Unconstrained Open Wire Basin (No Back Wall)
// Generated by Antigravity Imagineering Engine
// ============================================================================

$fn = 24;

/* [Panel Geometry] */
front_thickness       = 2.0;  // 2.0mm solid general front plate
pocket_floor_z        = 1.0;  // 1.0mm plate thickness directly under LED pockets
perimeter_rim_height  = 4.0;  // 4.0mm tall outer perimeter rim
total_thickness       = 6.0;  // 6.0mm overall armor plate height (Z = 0 to 6.0mm)
rim_wall_thickness    = 2.5;  // 2.5mm outer rim wall width
panel_width_mm        = {specs['panel_width_mm']};
panel_height_mm       = {specs['panel_height_mm']};

/* [LED Socket Collars (10mm x 5mm Resin Pixels)] */
collar_height         = 3.0;  // 3.0mm tall socket walls (rising from Z = 1.0 to 4.0mm)
collar_inner_length   = 10.0; // 10.0mm inner cavity length
collar_inner_width    = 5.0;  // 5.0mm inner cavity width
collar_wall_thickness = 1.2;  // 1.2mm collar wall thickness
notch_width           = 4.0;  // 4.0mm wire pass-through opening on both 5mm ends
window_square         = 2.0;  // 2.0mm x 2.0mm square optical window through 1mm floor

/* [Outside Fastener Eyelet Tabs] */
fastener_hole_dia     = 2.5;  // 2.5mm through-hole for thread or tagging barb
fastener_tab_od       = 6.5;  // 6.5mm outer tab diameter (2.0mm wall thickness)
fastener_tab_height   = 4.0;  // 4.0mm tall (Z = 0.0 to 4.0mm)

// 2D Contour Coordinates for Solid Plate Perimeter
contour_pts = {contour_pts};

// 100 LED Bulb Coordinates
ordered_leds = {[ [round(l['x'], 2), round(l['y'], 2)] for l in ordered_leds ]};

// 100 Path Tangent Rotation Angles (degrees)
led_rotations = {led_rotations_deg};

// 100 Debossed LED Number Positions
number_positions = {number_positions};

// 16 Outside Perimeter Fastener Tab Centers
fastener_tabs = {fastener_tabs};

// Module for 2D stadium/oval
module stadium_2d(length, width) {{
    hull() {{
        translate([-(length - width)/2, 0])
            circle(d = width);
        translate([(length - width)/2, 0])
            circle(d = width);
    }}
}}

// Module for single notched oval collar (Z = 1.0 to 4.0mm)
module single_collar() {{
    difference() {{
        // Outer oval collar wall
        linear_extrude(height = collar_height)
            stadium_2d(collar_inner_length + 2 * collar_wall_thickness, collar_inner_width + 2 * collar_wall_thickness);
        
        // Inner 10x5mm cavity
        translate([0, 0, -0.1])
            linear_extrude(height = collar_height + 0.2)
                stadium_2d(collar_inner_length, collar_inner_width);
        
        // Wire pass-through notches on both 5mm ends down to floor
        translate([(collar_inner_length + collar_wall_thickness)/2, 0, collar_height/2])
            cube([collar_wall_thickness * 2 + 1, notch_width, collar_height + 0.2], center = true);
        
        translate([-(collar_inner_length + collar_wall_thickness)/2, 0, collar_height/2])
            cube([collar_wall_thickness * 2 + 1, notch_width, collar_height + 0.2], center = true);
    }}
}}

module open_chassis_tpu_armor() {{
    difference() {{
        union() {{
            // 1. SOLID CONTINUOUS BASE PLATE (Z = 0 to 2.0mm)
            linear_extrude(height = front_thickness, convexity = 10)
                polygon(points = contour_pts);

            // 2. 4.0mm PERIMETER WALL RIM (Z = 2.0 to 6.0mm)
            translate([0, 0, front_thickness])
                linear_extrude(height = perimeter_rim_height, convexity = 10)
                    difference() {{
                        polygon(points = contour_pts);
                        offset(r = -rim_wall_thickness)
                            polygon(points = contour_pts);
                    }}

            // 3. 16 OUTSIDE PERIMETER FASTENER TABS (Z = 0 to 4.0mm)
            for (i = [0 : len(fastener_tabs)-1]) {{
                translate([fastener_tabs[i][0], fastener_tabs[i][1], 0])
                    difference() {{
                        cylinder(d = fastener_tab_od, h = fastener_tab_height);
                        translate([0, 0, -0.1])
                            cylinder(d = fastener_hole_dia, h = fastener_tab_height + 0.2);
                    }}
            }}

            // 4. 100 NOTCHED OVAL COLLARS (Z = 1.0 to 4.0mm)
            for (i = [0 : len(ordered_leds)-1]) {{
                translate([ordered_leds[i][0], ordered_leds[i][1], pocket_floor_z])
                    rotate([0, 0, led_rotations[i]])
                        single_collar();
            }}
        }}

        // 5. 1.0mm RECESS CUTTERS IN FLOOR UNDER POCKETS (Z = 1.0 to 2.1mm)
        for (i = [0 : len(ordered_leds)-1]) {{
            translate([ordered_leds[i][0], ordered_leds[i][1], pocket_floor_z])
                rotate([0, 0, led_rotations[i]])
                    linear_extrude(height = front_thickness - pocket_floor_z + 0.1)
                        stadium_2d(collar_inner_length, collar_inner_width);
        }}

        // 6. 2x2mm SQUARE OPTICAL WINDOWS (Through front plate Z = -0.5 to 1.5mm)
        for (i = [0 : len(ordered_leds)-1]) {{
            translate([ordered_leds[i][0], ordered_leds[i][1], -0.2])
                rotate([0, 0, led_rotations[i]])
                    linear_extrude(height = pocket_floor_z + 0.4)
                        square([window_square, window_square], center = true);
        }}

        // 7. DEBOSSED LED NUMBERS 1-100 ON INNER FLOOR (Z = 1.4 to 2.1mm)
        for (i = [0 : len(number_positions)-1]) {{
            translate([number_positions[i][0], number_positions[i][1], front_thickness - 0.6])
                linear_extrude(height = 0.8)
                    text(str(i + 1), size = 2.8, valign = "center", halign = "center", font = "Liberation Sans:style=Bold");
        }}
    }}
}}

open_chassis_tpu_armor();
'''

with open('3d_panels/petes_dragon_tpu_panel.scad', 'w', encoding='utf-8') as f:
    f.write(scad_code)
print("Updated 3d_panels/petes_dragon_tpu_panel.scad successfully!")
