import json

with open('3d_panels/petes_dragon_specs.json') as f:
    specs = json.load(f)

contour_pts = specs['contour_pts']
ordered_leds = specs['ordered_leds']
expansion_wells = specs['expansion_wells']
number_positions = specs['number_positions']
fastener_tabs = specs['fastener_tabs']

scad_code = f'''// ============================================================================
// 🏰 Main Street Electrical Parade (WDW 10K) - Flexible TPU Chest Panel
// Character: Pete's Dragon (Elliott) - 100 Addressable Fairy Light Bulbs
// Sized for Snapmaker U1 | Material: 95A TPU | Fasteners: 10mm Garment Barbs
// Hardware Architecture: 5.5mm Armor Plate with 4.5mm On-Edge Slack Expansion Wells
// 10mm x 5mm Oval LED Sockets | Debossed LED Numbers 1-100
// Generated by Antigravity Imagineering Engine
// ============================================================================

$fn = 24;

/* [Panel Geometry] */
panel_thickness       = 5.5;  // 5.5mm wearable plate for deep on-edge slack absorption
panel_width_mm        = {specs['panel_width_mm']};
panel_height_mm       = {specs['panel_height_mm']};

/* [LED Sockets (10mm x 5mm Resin Pixels)] */
led_pocket_length     = 10.5; // 10.5mm long
led_pocket_width      = 5.5;  // 5.5mm wide
led_pocket_depth      = 3.0;  // 3.0mm deep from back face (Z = 0)
led_window_length     = 5.6;  // 5.6mm long front optical window
led_window_width      = 3.2;  // 3.2mm wide front optical window

/* [On-Edge Slack Expansion Wells] */
expansion_well_dia    = 7.5;  // 7.5mm diameter
expansion_well_depth  = 4.5;  // 4.5mm deep (houses 4.0mm ribbon on its edge)

/* [Fastener Eyelets] */
fastener_hole_dia     = 2.5;  // 2.5mm through-hole for tagging needle / thread
fastener_csk_dia      = 5.0;  // 5.0mm front countersink
fastener_csk_depth    = 1.0;  // 1.0mm front countersink depth

// 2D Contour Coordinates for Solid Continuous Wearable Plate
contour_pts = {contour_pts};

// 100 LED Bulb Coordinates
ordered_leds = {[ [round(l['x'], 2), round(l['y'], 2)] for l in ordered_leds ]};

// 100 On-Edge Slack Expansion Well Centers
expansion_wells = {expansion_wells};

// 100 Debossed LED Number Positions
number_positions = {number_positions};

// 16 Perimeter Fastener Tabs
fastener_tabs = {fastener_tabs};

// Module for stadium/oval shape
module oval_prism(length, width, height) {{
    hull() {{
        translate([-(length - width)/2, 0, 0])
            cylinder(d = width, h = height, center = false);
        translate([(length - width)/2, 0, 0])
            cylinder(d = width, h = height, center = false);
    }}
}}

module tpu_chest_panel() {{
    difference() {{
        // 1. SOLID BASE PLATE (Extruded from Z = 0 to panel_thickness)
        linear_extrude(height = panel_thickness, convexity = 10)
            polygon(points = contour_pts);

        // 2. FRONT OPTICAL APERTURES (Through plate from Z = -0.5 to panel_thickness + 0.5)
        for (i = [0 : len(ordered_leds)-1]) {{
            translate([ordered_leds[i][0], ordered_leds[i][1], -0.5])
                oval_prism(led_window_length, led_window_width, panel_thickness + 1.0);
        }}

        // 3. REAR LED BULB POCKETS (Sunken from back face Z = -0.1 to led_pocket_depth)
        for (i = [0 : len(ordered_leds)-1]) {{
            translate([ordered_leds[i][0], ordered_leds[i][1], -0.1])
                oval_prism(led_pocket_length, led_pocket_width, led_pocket_depth + 0.1);
        }}

        // 4. ON-EDGE SLACK EXPANSION WELLS (Sunken 4.5mm deep from back face Z = -0.1)
        for (i = [0 : len(expansion_wells)-1]) {{
            translate([expansion_wells[i][0], expansion_wells[i][1], -0.1])
                cylinder(d = expansion_well_dia, h = expansion_well_depth + 0.1);
        }}

        // 5. CLEAR IMPRINTED DEBOSSED LED NUMBERS (1 to 100)
        for (i = [0 : len(number_positions)-1]) {{
            translate([number_positions[i][0], number_positions[i][1], -0.1])
                linear_extrude(height = 0.9)
                    text(str(i + 1), size = 3.0, valign = "center", halign = "center", font = "Liberation Sans:style=Bold");
        }}

        // 6. PERIMETER FASTENER EYELETS (16 along border)
        for (i = [0 : len(fastener_tabs)-1]) {{
            // Through hole
            translate([fastener_tabs[i][0], fastener_tabs[i][1], -0.5])
                cylinder(d = fastener_hole_dia, h = panel_thickness + 1.0);
            
            // Front countersink
            translate([fastener_tabs[i][0], fastener_tabs[i][1], panel_thickness - fastener_csk_depth])
                cylinder(d = fastener_csk_dia, h = fastener_csk_depth + 0.5);
        }}
    }}
}}

tpu_chest_panel();
'''

with open('3d_panels/petes_dragon_tpu_panel.scad', 'w', encoding='utf-8') as f:
    f.write(scad_code)
print("Updated 3d_panels/petes_dragon_tpu_panel.scad successfully!")
