// ============================================================================
// 🏰 Main Street Electrical Parade (WDW 10K) - Flexible TPU Chest Armor Tray
// Character: Pete's Dragon (Elliott) - 100 Addressable Fairy Light Bulbs
// Sized for Snapmaker U1 | Material: 95A TPU | Fasteners: Backside Rim Eyelets
// Hardware Architecture: 6.0mm Open Chassis Tray (2mm Front Plate + 4mm Perimeter Rim)
// Cross Section:
//   - General Tray Floor: 2.0mm
//   - LED Pocket Floor: 1.0mm (1.0mm interior pocket recess)
//   - LED Socket Collars: 3.0mm tall (Z = 1.0 to 4.0mm)
//   - Clearance when laying front-side up: 2.0mm space under collars to table (Z = 4.0 to 6.0mm)
//   - Perimeter Rim: 4.0mm tall (Z = 2.0 to 6.0mm)
// 10mm x 5mm Rotated Oval Collars (3mm Tall) with 4mm Wire Notches
// 2mm x 2mm Square Optical Windows | Etched Numbers 1-100 on Inner Floor
// Unconstrained Open Wire Basin (No Back Wall)
// Generated by Antigravity Imagineering Engine
// ============================================================================

$fn = 24;

/* [Panel Geometry] */
front_thickness       = 2.0;  // 2.0mm solid general front plate
pocket_floor_z        = 1.0;  // 1.0mm plate thickness directly under LED pockets
perimeter_rim_height  = 4.0;  // 4.0mm tall outer perimeter rim
total_thickness       = 6.0;  // 6.0mm overall armor plate height (Z = 0 to 6.0mm)
rim_wall_thickness    = 2.5;  // 2.5mm outer rim wall width
panel_width_mm        = 166.09;
panel_height_mm       = 151.99;

/* [LED Socket Collars (10mm x 5mm Resin Pixels)] */
collar_height         = 3.0;  // 3.0mm tall socket walls (rising from Z = 1.0 to 4.0mm)
collar_inner_length   = 10.0; // 10.0mm inner cavity length
collar_inner_width    = 5.0;  // 5.0mm inner cavity width
collar_wall_thickness = 1.2;  // 1.2mm collar wall thickness
notch_width           = 4.0;  // 4.0mm wire pass-through opening on both 5mm ends
window_square         = 2.0;  // 2.0mm x 2.0mm square optical window through 1mm floor

/* [Backside Rim Fastener Tabs] */
fastener_hole_dia     = 2.5;  // 2.5mm through-hole for thread or tagging barb
fastener_tab_od       = 6.0;  // 6.0mm outer tab diameter
fastener_tab_height   = 3.0;  // 3.0mm tall (Z = 2.0 to 5.0mm)

// 2D Contour Coordinates for Solid Plate Perimeter
contour_pts = [[82.05, 135.5], [86.13, 148.0], [88.0, 149.98], [103.07, 151.23], [104.84, 150.56], [109.14, 147.0], [110.8, 149.3], [117.95, 153.09], [119.34, 157.25], [113.37, 161.63], [112.09, 163.94], [112.28, 174.65], [112.98, 176.47], [114.47, 177.74], [127.42, 178.93], [132.13, 183.04], [134.64, 183.8], [163.8, 179.78], [165.18, 179.16], [166.43, 177.73], [166.81, 175.14], [163.65, 158.63], [167.72, 156.1], [168.81, 153.72], [172.08, 119.52], [169.73, 112.56], [168.58, 111.13], [159.38, 105.28], [157.24, 104.66], [140.57, 104.8], [133.71, 107.4], [130.47, 111.13], [121.36, 92.6], [121.76, 77.84], [118.93, 68.94], [122.99, 63.01], [130.44, 58.23], [131.64, 56.65], [131.96, 40.56], [131.08, 38.06], [128.45, 36.59], [110.99, 36.13], [109.53, 36.51], [104.96, 39.24], [90.54, 37.51], [88.67, 33.63], [86.32, 32.1], [71.83, 31.81], [53.64, 35.66], [51.68, 37.06], [50.61, 39.53], [13.56, 44.62], [11.75, 45.34], [10.5, 46.84], [10.11, 48.35], [8.36, 78.89], [13.86, 95.28], [13.23, 98.44], [8.85, 99.98], [7.67, 101.02], [6.97, 102.43], [5.99, 117.75], [6.83, 120.46], [10.99, 125.74], [13.48, 126.95], [22.39, 126.8], [32.6, 120.31], [34.32, 121.83], [40.4, 123.98], [39.23, 138.05], [42.41, 144.55], [42.59, 153.89], [43.65, 155.59], [45.8, 156.64], [59.61, 158.59], [69.33, 153.92], [80.58, 139.88], [82.05, 135.5]];

// 100 LED Bulb Coordinates
ordered_leds = [[18.66, 52.49], [53.74, 107.87], [32.51, 50.76], [72.47, 93.22], [124.02, 136.48], [60.2, 125.18], [70.81, 59.99], [110.96, 114.22], [135.23, 153.79], [93.88, 137.29], [160.34, 149.41], [103.11, 140.18], [53.74, 96.91], [114.19, 130.95], [64.81, 87.68], [118.8, 139.02], [63.43, 101.53], [98.5, 46.15], [74.96, 103.37], [132.65, 143.64], [101.73, 84.8], [140.49, 139.02], [75.43, 115.95], [129.42, 155.75], [91.12, 100.37], [32.51, 68.07], [100.35, 73.84], [47.74, 117.1], [80.04, 59.99], [21.43, 83.93], [86.5, 68.07], [120.19, 123.45], [157.11, 172.48], [141.88, 114.22], [146.49, 171.33], [120.19, 114.22], [74.04, 70.95], [21.43, 103.26], [60.2, 50.76], [64.81, 112.49], [24.71, 59.24], [97.11, 59.99], [41.14, 87.11], [81.89, 41.53], [31.86, 79.61], [58.35, 137.29], [37.72, 71.88], [110.96, 73.84], [145.11, 130.95], [92.5, 87.68], [151.11, 120.56], [135.88, 174.21], [161.72, 118.83], [121.57, 169.6], [157.11, 129.79], [91.12, 115.95], [145.34, 159.73], [100.35, 110.76], [32.51, 103.26], [72.66, 50.76], [43.12, 106.14], [83.27, 50.76], [30.66, 92.3], [70.81, 41.53], [103.11, 96.91], [144.14, 149.81], [74.04, 126.33], [140.49, 123.45], [110.96, 63.45], [41.74, 64.61], [110.96, 49.61], [59.5, 90.34], [49.12, 134.41], [19.59, 78.68], [83.27, 97.26], [23.09, 72.22], [87.89, 78.45], [125.22, 129.27], [79.44, 82.2], [26.05, 110.76], [50.97, 49.61], [120.19, 54.22], [83.27, 109.6], [46.35, 57.11], [15.43, 114.22], [56.97, 63.45], [123.42, 44.99], [63.43, 75.57], [106.34, 125.18], [49.26, 86.99], [56.97, 149.41], [56.46, 77.99], [68.04, 140.18], [131.26, 164.98], [115.57, 103.26], [152.35, 152.64], [92.5, 126.33], [160.34, 140.18], [112.34, 84.8], [151.34, 137.52]];

// 100 Path Tangent Rotation Angles (degrees)
led_rotations = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];

// 100 Debossed LED Number Positions
number_positions = [[12.16, 47.99], [53.74, 113.37], [32.51, 45.26], [72.47, 87.72], [132.02, 136.48], [52.2, 125.18], [64.31, 64.49], [110.96, 119.72], [135.23, 159.29], [87.38, 141.79], [166.84, 153.91], [103.11, 145.68], [45.74, 96.91], [107.69, 135.45], [71.31, 83.18], [112.3, 143.52], [63.43, 96.03], [98.5, 40.65], [74.96, 108.87], [126.15, 148.14], [95.23, 80.3], [133.99, 134.52], [81.93, 120.45], [121.42, 155.75], [91.12, 105.87], [32.51, 62.57], [100.35, 68.34], [41.24, 121.6], [88.04, 59.99], [14.93, 88.43], [94.5, 68.07], [126.69, 118.95], [165.11, 172.48], [141.88, 108.72], [146.49, 176.83], [126.69, 109.72], [74.04, 76.45], [14.93, 98.76], [60.2, 45.26], [64.81, 117.99], [18.21, 63.74], [103.61, 55.49], [41.14, 92.61], [88.39, 37.03], [39.86, 79.61], [64.85, 132.79], [44.22, 76.38], [118.96, 73.84], [137.11, 130.95], [84.5, 87.68], [151.11, 115.06], [135.88, 179.71], [168.22, 114.33], [115.07, 174.1], [165.11, 129.79], [84.62, 120.45], [151.84, 164.23], [100.35, 116.26], [39.01, 98.76], [66.16, 55.26], [43.12, 100.64], [89.77, 55.26], [22.66, 92.3], [64.31, 37.03], [103.11, 102.41], [150.64, 145.31], [80.54, 130.83], [132.49, 123.45], [118.96, 63.45], [48.24, 69.11], [110.96, 44.11], [66.0, 94.84], [41.12, 134.41], [11.59, 78.68], [83.27, 91.76], [16.59, 67.72], [81.39, 73.95], [133.22, 129.27], [79.44, 87.7], [32.55, 115.26], [44.47, 45.11], [126.69, 58.72], [83.27, 115.1], [38.35, 57.11], [8.93, 118.72], [50.47, 67.95], [129.92, 40.49], [63.43, 70.07], [99.84, 120.68], [49.26, 81.49], [50.47, 153.91], [49.96, 73.49], [74.54, 144.68], [139.26, 164.98], [122.07, 98.76], [152.35, 147.14], [84.5, 126.33], [168.34, 140.18], [120.34, 84.8], [151.34, 143.02]];

// 16 Backside Rim Fastener Tab Centers
fastener_tabs = [[78.25, 136.74], [112.97, 145.81], [118.35, 174.08], [156.53, 176.75], [165.21, 149.4], [165.23, 113.75], [126.73, 112.6], [116.16, 73.42], [128.44, 41.16], [87.05, 39.39], [55.35, 39.36], [15.08, 48.44], [13.49, 81.59], [10.26, 118.02], [44.35, 124.76], [52.65, 153.57]];

// Module for 2D stadium/oval
module stadium_2d(length, width) {
    hull() {
        translate([-(length - width)/2, 0])
            circle(d = width);
        translate([(length - width)/2, 0])
            circle(d = width);
    }
}

// Module for single notched oval collar (Z = 1.0 to 4.0mm)
module single_collar() {
    difference() {
        // Outer oval collar wall
        linear_extrude(height = collar_height)
            stadium_2d(collar_inner_length + 2 * collar_wall_thickness, collar_inner_width + 2 * collar_wall_thickness);
        
        // Inner 10x5mm cavity
        translate([0, 0, -0.1])
            linear_extrude(height = collar_height + 0.2)
                stadium_2d(collar_inner_length, collar_inner_width);
        
        // Wire pass-through notches on both 5mm ends down to floor
        translate([(collar_inner_length + collar_wall_thickness)/2, 0, collar_height/2])
            cube([collar_wall_thickness * 2 + 1, notch_width, collar_height + 0.2], center = true);
        
        translate([-(collar_inner_length + collar_wall_thickness)/2, 0, collar_height/2])
            cube([collar_wall_thickness * 2 + 1, notch_width, collar_height + 0.2], center = true);
    }
}

module open_chassis_tpu_armor() {
    difference() {
        union() {
            // 1. SOLID CONTINUOUS BASE PLATE (Z = 0 to 2.0mm)
            linear_extrude(height = front_thickness, convexity = 10)
                polygon(points = contour_pts);

            // 2. 4.0mm PERIMETER WALL RIM (Z = 2.0 to 6.0mm)
            translate([0, 0, front_thickness])
                linear_extrude(height = perimeter_rim_height, convexity = 10)
                    difference() {
                        polygon(points = contour_pts);
                        offset(r = -rim_wall_thickness)
                            polygon(points = contour_pts);
                    }

            // 3. 16 BACKSIDE RIM FASTENER TABS (Z = 2.0 to 5.0mm)
            for (i = [0 : len(fastener_tabs)-1]) {
                translate([fastener_tabs[i][0], fastener_tabs[i][1], front_thickness])
                    difference() {
                        cylinder(d = fastener_tab_od, h = fastener_tab_height);
                        translate([0, 0, -0.1])
                            cylinder(d = fastener_hole_dia, h = fastener_tab_height + 0.2);
                    }
            }

            // 4. 100 NOTCHED OVAL COLLARS (Z = 1.0 to 4.0mm)
            for (i = [0 : len(ordered_leds)-1]) {
                translate([ordered_leds[i][0], ordered_leds[i][1], pocket_floor_z])
                    rotate([0, 0, led_rotations[i]])
                        single_collar();
            }
        }

        // 5. 1.0mm RECESS CUTTERS IN FLOOR UNDER POCKETS (Z = 1.0 to 2.1mm)
        for (i = [0 : len(ordered_leds)-1]) {
            translate([ordered_leds[i][0], ordered_leds[i][1], pocket_floor_z])
                rotate([0, 0, led_rotations[i]])
                    linear_extrude(height = front_thickness - pocket_floor_z + 0.1)
                        stadium_2d(collar_inner_length, collar_inner_width);
        }

        // 6. 2x2mm SQUARE OPTICAL WINDOWS (Through front plate Z = -0.5 to 1.5mm)
        for (i = [0 : len(ordered_leds)-1]) {
            translate([ordered_leds[i][0], ordered_leds[i][1], -0.2])
                rotate([0, 0, led_rotations[i]])
                    linear_extrude(height = pocket_floor_z + 0.4)
                        square([window_square, window_square], center = true);
        }

        // 7. DEBOSSED LED NUMBERS 1-100 ON INNER FLOOR (Z = 1.4 to 2.1mm)
        for (i = [0 : len(number_positions)-1]) {
            translate([number_positions[i][0], number_positions[i][1], front_thickness - 0.6])
                linear_extrude(height = 0.8)
                    text(str(i + 1), size = 2.8, valign = "center", halign = "center", font = "Liberation Sans:style=Bold");
        }
    }
}

open_chassis_tpu_armor();
