// ============================================================================
// 🏰 Main Street Electrical Parade (WDW 10K) - Flexible TPU Chest Armor Tray
// Character: Pete's Dragon (Elliott) - 100 Addressable Fairy Light Bulbs
// Sized for Snapmaker U1 | Material: 95A TPU | Fasteners: Backside Rim Eyelets
// Hardware Architecture: 6.0mm Open Chassis Tray (2mm Front Plate + 4mm Perimeter Rim)
// Cross Section:
//   - General Tray Floor: 2.0mm
//   - LED Pocket Floor: 1.0mm (1.0mm interior pocket recess)
//   - LED Socket Collars: 3.0mm tall (Z = 1.0 to 4.0mm)
//   - Clearance when laying front-side up: 2.0mm space under collars to table (Z = 4.0 to 6.0mm)
//   - Perimeter Rim: 4.0mm tall (Z = 2.0 to 6.0mm)
// 10mm x 5mm Rotated Oval Collars (3mm Tall) with 4mm Wire Notches
// 2mm x 2mm Square Optical Windows | Etched Numbers 1-100 on Inner Floor
// Unconstrained Open Wire Basin (No Back Wall)
// Generated by Antigravity Imagineering Engine
// ============================================================================

$fn = 24;

/* [Panel Geometry] */
front_thickness       = 2.0;  // 2.0mm solid general front plate
pocket_floor_z        = 1.0;  // 1.0mm plate thickness directly under LED pockets
perimeter_rim_height  = 4.0;  // 4.0mm tall outer perimeter rim
total_thickness       = 6.0;  // 6.0mm overall armor plate height (Z = 0 to 6.0mm)
rim_wall_thickness    = 2.5;  // 2.5mm outer rim wall width
panel_width_mm        = 213.07;
panel_height_mm       = 199.02;

/* [LED Socket Collars (10mm x 5mm Resin Pixels)] */
collar_height         = 3.0;  // 3.0mm tall socket walls (rising from Z = 1.0 to 4.0mm)
collar_inner_length   = 10.0; // 10.0mm inner cavity length
collar_inner_width    = 5.0;  // 5.0mm inner cavity width
collar_wall_thickness = 1.2;  // 1.2mm collar wall thickness
notch_width           = 4.0;  // 4.0mm wire pass-through opening on both 5mm ends
window_square         = 2.0;  // 2.0mm x 2.0mm square optical window through 1mm floor

/* [Backside Rim Fastener Tabs] */
fastener_hole_dia     = 2.5;  // 2.5mm through-hole for thread or tagging barb
fastener_tab_od       = 6.0;  // 6.0mm outer tab diameter
fastener_tab_height   = 3.0;  // 3.0mm tall (Z = 2.0 to 5.0mm)

// 2D Contour Coordinates for Solid Plate Perimeter
contour_pts = [[4.22, 146.07], [18.88, 149.87], [19.87, 151.19], [20.68, 155.27], [25.08, 165.82], [32.16, 173.4], [44.9, 180.61], [58.51, 182.78], [67.41, 181.14], [75.19, 176.97], [77.23, 176.74], [89.98, 181.92], [93.04, 186.71], [100.39, 195.3], [103.43, 197.57], [112.15, 201.65], [118.27, 202.71], [130.95, 207.25], [141.88, 207.02], [148.72, 205.05], [154.85, 205.76], [166.46, 204.51], [179.29, 197.55], [188.06, 184.98], [190.54, 172.86], [189.76, 164.35], [193.52, 153.53], [193.75, 138.41], [193.0, 133.05], [195.12, 119.28], [193.81, 109.64], [186.64, 96.73], [184.89, 94.83], [175.48, 88.35], [168.09, 86.15], [160.98, 83.05], [155.6, 82.34], [153.82, 80.8], [149.69, 70.58], [155.82, 53.27], [156.61, 41.49], [152.04, 27.88], [145.57, 19.92], [136.48, 14.19], [127.68, 11.78], [118.97, 11.85], [108.41, 14.27], [103.96, 13.13], [98.15, 12.69], [88.1, 8.63], [67.5, 8.22], [58.06, 10.64], [52.85, 13.4], [48.22, 14.71], [40.46, 18.08], [29.44, 17.41], [22.21, 19.27], [14.71, 19.38], [4.03, 22.65], [-0.61, 25.35], [-10.34, 35.89], [-14.66, 50.42], [-13.89, 60.06], [-12.46, 66.12], [-13.58, 74.3], [-13.62, 82.66], [-11.63, 92.43], [-16.07, 103.12], [-17.95, 113.97], [-16.17, 125.26], [-10.01, 135.84], [4.22, 146.07]];

// 100 LED Bulb Coordinates
ordered_leds = [[18.66, 52.49], [53.74, 107.87], [32.51, 50.76], [72.47, 93.22], [124.02, 136.48], [60.2, 125.18], [70.81, 59.99], [110.96, 114.22], [135.23, 153.79], [93.88, 137.29], [160.34, 149.41], [103.11, 140.18], [53.74, 96.91], [114.19, 130.95], [64.81, 87.68], [118.8, 139.02], [63.43, 101.53], [98.5, 46.15], [74.96, 103.37], [132.65, 143.64], [101.73, 84.8], [140.49, 139.02], [75.43, 115.95], [129.42, 155.75], [91.12, 100.37], [32.51, 68.07], [100.35, 73.84], [47.74, 117.1], [80.04, 59.99], [21.43, 83.93], [86.5, 68.07], [120.19, 123.45], [157.11, 172.48], [141.88, 114.22], [146.49, 171.33], [120.19, 114.22], [74.04, 70.95], [21.43, 103.26], [60.2, 50.76], [64.81, 112.49], [24.71, 59.24], [97.11, 59.99], [41.14, 87.11], [81.89, 41.53], [31.86, 79.61], [58.35, 137.29], [37.72, 71.88], [110.96, 73.84], [145.11, 130.95], [92.5, 87.68], [151.11, 120.56], [135.88, 174.21], [161.72, 118.83], [121.57, 169.6], [157.11, 129.79], [91.12, 115.95], [145.34, 159.73], [100.35, 110.76], [32.51, 103.26], [72.66, 50.76], [43.12, 106.14], [83.27, 50.76], [30.66, 92.3], [70.81, 41.53], [103.11, 96.91], [144.14, 149.81], [74.04, 126.33], [140.49, 123.45], [110.96, 63.45], [41.74, 64.61], [110.96, 49.61], [59.5, 90.34], [49.12, 134.41], [19.59, 78.68], [83.27, 97.26], [23.09, 72.22], [87.89, 78.45], [125.22, 129.27], [79.44, 82.2], [26.05, 110.76], [50.97, 49.61], [120.19, 54.22], [83.27, 109.6], [46.35, 57.11], [15.43, 114.22], [56.97, 63.45], [123.42, 44.99], [63.43, 75.57], [106.34, 125.18], [49.26, 86.99], [56.97, 149.41], [56.46, 77.99], [68.04, 140.18], [131.26, 164.98], [115.57, 103.26], [152.35, 152.64], [92.5, 126.33], [160.34, 140.18], [112.34, 84.8], [151.34, 137.52]];

// 100 Path Tangent Rotation Angles (degrees)
led_rotations = [57.6, -110.4, 46.7, 40.0, -170.0, -80.8, 53.5, 58.5, -158.2, 10.3, -170.8, -138.8, 29.4, -138.8, 43.6, -145.9, -57.7, 112.4, 34.9, -117.7, 54.4, -160.5, 36.4, -124.7, -151.1, 4.9, 140.6, -60.5, 157.8, -13.7, 58.7, 53.0, -104.7, 85.4, -114.7, -136.8, 148.4, -53.6, 85.7, -127.0, 0.6, 154.1, -48.2, 142.7, 65.3, -107.5, 1.5, 59.1, -140.6, 29.3, 105.8, -65.0, 128.3, -48.2, -168.2, 38.9, -132.6, -173.7, -52.6, 118.1, -54.1, 141.7, -51.7, 59.7, 52.2, -161.5, -2.5, -116.2, 179.0, -12.2, 141.6, 103.3, -117.9, 16.3, -157.4, 5.5, 53.7, -134.2, 151.9, -67.8, 3.8, 123.7, -125.1, 118.4, -50.7, -15.5, 153.0, 49.1, -146.2, 83.0, -90.4, 79.5, 21.4, -104.3, 53.3, -156.3, 11.5, -130.9, 53.5, 53.5];

// 100 Debossed LED Number Positions
number_positions = [[12.32, 51.07], [47.65, 110.13], [32.71, 44.26], [71.9, 86.74], [122.89, 142.88], [53.78, 124.14], [64.38, 59.03], [105.42, 117.62], [137.8, 159.76], [88.53, 140.99], [164.15, 154.68], [103.54, 146.67], [47.48, 98.66], [109.91, 135.84], [69.29, 82.97], [115.16, 144.4], [68.92, 105.01], [96.0, 40.15], [71.24, 108.7], [126.9, 146.66], [107.02, 81.02], [137.69, 133.15], [74.46, 109.52], [123.03, 154.58], [92.93, 106.61], [33.06, 61.59], [96.22, 68.82], [41.48, 118.84], [77.52, 65.98], [18.05, 89.48], [92.82, 69.61], [113.75, 122.54], [163.4, 170.84], [136.93, 110.01], [144.24, 177.43], [126.69, 114.01], [72.53, 77.27], [16.2, 99.4], [55.96, 55.69], [59.62, 116.4], [20.07, 63.79], [90.97, 57.86], [41.5, 93.6], [82.76, 35.09], [29.6, 85.7], [55.35, 143.06], [42.19, 76.6], [117.26, 75.43], [138.64, 131.58], [86.24, 89.44], [147.94, 114.88], [138.1, 180.32], [168.18, 118.08], [115.08, 169.97], [162.55, 126.24], [87.04, 121.01], [140.55, 164.13], [105.42, 106.7], [33.37, 109.7], [66.92, 47.7], [42.1, 99.72], [89.73, 51.52], [24.2, 93.05], [64.52, 39.88], [108.25, 92.93], [146.2, 143.65], [78.83, 130.72], [134.34, 121.36], [106.29, 58.93], [47.21, 68.13], [111.71, 43.15], [56.08, 84.81], [42.91, 132.5], [13.89, 81.8], [80.79, 91.25], [18.95, 67.21], [94.32, 79.43], [131.72, 129.36], [73.22, 80.32], [28.57, 116.75], [46.69, 44.72], [125.6, 57.83], [82.15, 116.0], [40.63, 54.02], [8.96, 114.87], [53.77, 69.11], [125.43, 38.81], [63.9, 69.09], [102.73, 130.58], [45.26, 92.11], [52.41, 154.04], [51.1, 74.31], [70.64, 146.14], [137.56, 163.38], [120.78, 99.38], [154.71, 158.7], [87.08, 129.91], [166.82, 140.64], [118.77, 85.76], [150.38, 143.95]];

// 16 Backside Rim Fastener Tab Centers
fastener_tabs = [[5.22, 142.2], [35.2, 170.52], [72.33, 173.96], [110.82, 196.62], [152.08, 201.41], [184.17, 183.58], [189.68, 142.74], [185.21, 102.39], [149.18, 80.01], [151.14, 37.78], [122.95, 15.82], [80.09, 12.47], [37.83, 21.93], [-0.27, 30.88], [-8.82, 69.05], [-13.54, 111.91]];

// Module for 2D stadium/oval
module stadium_2d(length, width) {
    hull() {
        translate([-(length - width)/2, 0])
            circle(d = width);
        translate([(length - width)/2, 0])
            circle(d = width);
    }
}

// Module for single notched oval collar (Z = 1.0 to 4.0mm)
module single_collar() {
    difference() {
        // Outer oval collar wall
        linear_extrude(height = collar_height)
            stadium_2d(collar_inner_length + 2 * collar_wall_thickness, collar_inner_width + 2 * collar_wall_thickness);
        
        // Inner 10x5mm cavity
        translate([0, 0, -0.1])
            linear_extrude(height = collar_height + 0.2)
                stadium_2d(collar_inner_length, collar_inner_width);
        
        // Wire pass-through notches on both 5mm ends down to floor
        translate([(collar_inner_length + collar_wall_thickness)/2, 0, collar_height/2])
            cube([collar_wall_thickness * 2 + 1, notch_width, collar_height + 0.2], center = true);
        
        translate([-(collar_inner_length + collar_wall_thickness)/2, 0, collar_height/2])
            cube([collar_wall_thickness * 2 + 1, notch_width, collar_height + 0.2], center = true);
    }
}

module open_chassis_tpu_armor() {
    difference() {
        union() {
            // 1. SOLID CONTINUOUS BASE PLATE (Z = 0 to 2.0mm)
            linear_extrude(height = front_thickness, convexity = 10)
                polygon(points = contour_pts);

            // 2. 4.0mm PERIMETER WALL RIM (Z = 2.0 to 6.0mm)
            translate([0, 0, front_thickness])
                linear_extrude(height = perimeter_rim_height, convexity = 10)
                    difference() {
                        polygon(points = contour_pts);
                        offset(r = -rim_wall_thickness)
                            polygon(points = contour_pts);
                    }

            // 3. 16 BACKSIDE RIM FASTENER TABS (Z = 2.0 to 5.0mm)
            for (i = [0 : len(fastener_tabs)-1]) {
                translate([fastener_tabs[i][0], fastener_tabs[i][1], front_thickness])
                    difference() {
                        cylinder(d = fastener_tab_od, h = fastener_tab_height);
                        translate([0, 0, -0.1])
                            cylinder(d = fastener_hole_dia, h = fastener_tab_height + 0.2);
                    }
            }

            // 4. 100 NOTCHED OVAL COLLARS (Z = 1.0 to 4.0mm)
            for (i = [0 : len(ordered_leds)-1]) {
                translate([ordered_leds[i][0], ordered_leds[i][1], pocket_floor_z])
                    rotate([0, 0, led_rotations[i]])
                        single_collar();
            }
        }

        // 5. 1.0mm RECESS CUTTERS IN FLOOR UNDER POCKETS (Z = 1.0 to 2.1mm)
        for (i = [0 : len(ordered_leds)-1]) {
            translate([ordered_leds[i][0], ordered_leds[i][1], pocket_floor_z])
                rotate([0, 0, led_rotations[i]])
                    linear_extrude(height = front_thickness - pocket_floor_z + 0.1)
                        stadium_2d(collar_inner_length, collar_inner_width);
        }

        // 6. 2x2mm SQUARE OPTICAL WINDOWS (Through front plate Z = -0.5 to 1.5mm)
        for (i = [0 : len(ordered_leds)-1]) {
            translate([ordered_leds[i][0], ordered_leds[i][1], -0.2])
                rotate([0, 0, led_rotations[i]])
                    linear_extrude(height = pocket_floor_z + 0.4)
                        square([window_square, window_square], center = true);
        }

        // 7. DEBOSSED LED NUMBERS 1-100 ON INNER FLOOR (Z = 1.4 to 2.1mm)
        for (i = [0 : len(number_positions)-1]) {
            translate([number_positions[i][0], number_positions[i][1], front_thickness - 0.6])
                linear_extrude(height = 0.8)
                    text(str(i + 1), size = 2.8, valign = "center", halign = "center", font = "Liberation Sans:style=Bold");
        }
    }
}

open_chassis_tpu_armor();
