// ============================================================================
// 🏰 Main Street Electrical Parade (WDW 10K) - Flexible TPU Chest Armor Tray
// Character: Pete's Dragon (Elliott) - 100 Addressable Fairy Light Bulbs
// Sized for Snapmaker U1 | Material: 95A TPU | Fasteners: Backside Rim Eyelets
// Hardware Architecture: 6.0mm Open Chassis Tray (2mm Front Plate + 4mm Perimeter Rim)
// Cross Section:
//   - General Tray Floor: 2.0mm
//   - LED Pocket Floor: 1.0mm (1.0mm interior pocket recess)
//   - LED Socket Collars: 3.0mm tall (Z = 1.0 to 4.0mm)
//   - Clearance when laying front-side up: 2.0mm space under collars to table (Z = 4.0 to 6.0mm)
//   - Perimeter Rim: 4.0mm tall (Z = 2.0 to 6.0mm)
// 10mm x 5mm Rotated Oval Collars (3mm Tall) with 4mm Wire Notches
// 2mm x 2mm Square Optical Windows | Etched Numbers 1-100 on Inner Floor
// Unconstrained Open Wire Basin (No Back Wall)
// Generated by Antigravity Imagineering Engine
// ============================================================================

$fn = 24;

/* [Panel Geometry] */
front_thickness       = 2.0;  // 2.0mm solid general front plate
pocket_floor_z        = 1.0;  // 1.0mm plate thickness directly under LED pockets
perimeter_rim_height  = 4.0;  // 4.0mm tall outer perimeter rim
total_thickness       = 6.0;  // 6.0mm overall armor plate height (Z = 0 to 6.0mm)
rim_wall_thickness    = 2.5;  // 2.5mm outer rim wall width
panel_width_mm        = 166.09;
panel_height_mm       = 151.99;

/* [LED Socket Collars (10mm x 5mm Resin Pixels)] */
collar_height         = 3.0;  // 3.0mm tall socket walls (rising from Z = 1.0 to 4.0mm)
collar_inner_length   = 10.0; // 10.0mm inner cavity length
collar_inner_width    = 5.0;  // 5.0mm inner cavity width
collar_wall_thickness = 1.2;  // 1.2mm collar wall thickness
notch_width           = 4.0;  // 4.0mm wire pass-through opening on both 5mm ends
window_square         = 2.0;  // 2.0mm x 2.0mm square optical window through 1mm floor

/* [Outside Fastener Eyelet Tabs (Flush with Backside Z = 6.0mm, Pure Round)] */
fastener_hole_dia     = 2.5;  // 2.5mm through-hole for thread or tagging barb
fastener_tab_od       = 6.5;  // 6.5mm outer tab diameter (2.0mm wall thickness)
fastener_tab_thick    = 2.0;  // 2.0mm tall pure circular ear (Z = 4.0 to 6.0mm) flush with back edge

// 2D Contour Coordinates for Solid Plate Perimeter
contour_pts = [[82.05, 135.5], [86.13, 148.0], [88.0, 149.98], [103.07, 151.23], [104.84, 150.56], [109.14, 147.0], [110.8, 149.3], [117.95, 153.09], [119.34, 157.25], [113.37, 161.63], [112.09, 163.94], [112.28, 174.65], [112.98, 176.47], [114.47, 177.74], [127.42, 178.93], [132.13, 183.04], [134.64, 183.8], [163.8, 179.78], [165.18, 179.16], [166.43, 177.73], [166.81, 175.14], [163.65, 158.63], [167.72, 156.1], [168.81, 153.72], [172.08, 119.52], [169.73, 112.56], [168.58, 111.13], [159.38, 105.28], [157.24, 104.66], [140.57, 104.8], [133.71, 107.4], [130.47, 111.13], [121.36, 92.6], [121.76, 77.84], [118.93, 68.94], [122.99, 63.01], [130.44, 58.23], [131.64, 56.65], [131.96, 40.56], [131.08, 38.06], [128.45, 36.59], [110.99, 36.13], [109.53, 36.51], [104.96, 39.24], [90.54, 37.51], [88.67, 33.63], [86.32, 32.1], [71.83, 31.81], [53.64, 35.66], [51.68, 37.06], [50.61, 39.53], [13.56, 44.62], [11.75, 45.34], [10.5, 46.84], [10.11, 48.35], [8.36, 78.89], [13.86, 95.28], [13.23, 98.44], [8.85, 99.98], [7.67, 101.02], [6.97, 102.43], [5.99, 117.75], [6.83, 120.46], [10.99, 125.74], [13.48, 126.95], [22.39, 126.8], [32.6, 120.31], [34.32, 121.83], [40.4, 123.98], [39.23, 138.05], [42.41, 144.55], [42.59, 153.89], [43.65, 155.59], [45.8, 156.64], [59.61, 158.59], [69.33, 153.92], [80.58, 139.88], [82.05, 135.5]];

// 100 LED Bulb Coordinates
ordered_leds = [[18.35, 50.01], [54.7, 107.96], [32.51, 50.76], [72.54, 92.52], [125.8, 136.47], [60.2, 125.18], [69.16, 59.79], [109.99, 115.5], [135.35, 152.27], [92.73, 136.51], [162.08, 149.32], [104.26, 140.96], [50.28, 99.61], [113.5, 131.8], [64.77, 84.15], [117.56, 143.75], [63.31, 100.94], [98.25, 46.05], [76.02, 102.66], [130.44, 144.37], [101.95, 82.59], [139.42, 137.47], [76.98, 117.84], [127.11, 159.47], [92.8, 102.63], [31.52, 65.33], [99.72, 73.14], [47.74, 117.1], [82.06, 59.91], [20.61, 86.96], [87.96, 67.76], [120.96, 120.67], [158.57, 172.83], [141.77, 113.77], [146.12, 170.23], [122.5, 112.77], [75.19, 69.14], [19.12, 103.18], [60.21, 52.07], [65.48, 113.35], [23.87, 57.89], [97.11, 59.99], [39.13, 87.71], [82.8, 41.53], [31.59, 80.23], [58.36, 137.52], [39.2, 72.77], [112.58, 73.87], [143.71, 129.57], [90.68, 87.4], [151.22, 120.6], [134.79, 175.26], [163.74, 118.17], [120.3, 170.53], [157.56, 128.98], [91.07, 117.82], [144.93, 162.22], [98.91, 110.45], [31.91, 101.85], [72.92, 50.36], [41.8, 108.05], [85.81, 50.8], [29.29, 93.95], [69.9, 41.53], [103.19, 96.85], [146.31, 146.37], [74.04, 126.33], [138.39, 121.67], [110.96, 63.45], [44.38, 64.58], [110.57, 49.02], [59.66, 93.04], [46.95, 132.9], [18.78, 79.06], [84.95, 95.26], [21.18, 71.16], [88.23, 77.65], [125.97, 128.57], [78.11, 83.67], [26.7, 110.71], [48.17, 48.48], [120.83, 54.92], [84.17, 109.9], [46.35, 56.67], [14.82, 114.58], [57.22, 63.56], [123.42, 44.99], [64.62, 74.75], [106.02, 124.3], [51.77, 85.68], [56.97, 149.41], [52.33, 77.78], [70.2, 141.46], [132.54, 167.36], [115.57, 103.26], [151.03, 154.39], [92.5, 126.33], [163.76, 141.42], [114.4, 85.2], [152.3, 136.88]];

// 100 Path Tangent Rotation Angles (degrees)
led_rotations = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];

// 100 Debossed LED Number Positions
number_positions = [[11.85, 45.51], [54.7, 113.46], [32.51, 45.26], [72.54, 87.02], [132.3, 131.97], [52.2, 125.18], [69.16, 65.29], [109.99, 110.0], [135.35, 157.77], [86.23, 141.01], [168.58, 153.82], [104.26, 146.46], [43.78, 95.11], [113.5, 126.3], [71.27, 79.65], [117.56, 149.25], [63.31, 106.44], [98.25, 40.55], [76.02, 108.16], [123.94, 148.87], [101.95, 88.09], [132.92, 132.97], [83.48, 122.34], [120.61, 154.97], [92.8, 97.13], [31.52, 70.83], [99.72, 67.64], [41.24, 121.6], [90.06, 59.91], [14.11, 91.46], [81.46, 72.26], [128.96, 120.67], [166.57, 172.83], [141.77, 108.27], [146.12, 175.73], [129.0, 108.27], [75.19, 74.64], [12.62, 98.68], [60.21, 46.57], [65.48, 118.85], [17.37, 62.39], [103.61, 55.49], [39.13, 93.21], [82.8, 36.03], [31.59, 74.73], [64.86, 133.02], [39.2, 78.27], [120.58, 73.87], [135.71, 129.57], [97.18, 91.9], [151.22, 115.1], [134.79, 180.76], [170.24, 113.67], [113.8, 175.03], [165.56, 128.98], [84.57, 122.32], [152.93, 162.22], [105.41, 105.95], [38.41, 97.35], [79.42, 54.86], [41.8, 102.55], [92.31, 55.3], [29.29, 88.45], [63.4, 37.03], [103.19, 102.35], [154.31, 146.37], [80.54, 130.83], [131.89, 117.17], [110.96, 57.95], [50.88, 69.08], [110.57, 43.52], [51.66, 93.04], [38.95, 132.9], [10.78, 79.06], [84.95, 100.76], [14.68, 66.66], [81.73, 73.15], [133.97, 128.57], [78.11, 78.17], [26.7, 116.21], [48.17, 42.98], [127.33, 59.42], [84.17, 104.4], [38.35, 56.67], [8.32, 119.08], [57.22, 69.06], [129.92, 40.49], [64.62, 69.25], [99.52, 119.8], [51.77, 91.18], [50.47, 153.91], [52.33, 72.28], [76.7, 145.96], [140.54, 167.36], [122.07, 98.76], [157.53, 158.89], [84.5, 126.33], [170.26, 136.92], [122.4, 85.2], [152.3, 142.38]];

// 16 Outside Perimeter Fastener Tab Centers
fastener_tabs = [[83.48, 135.03], [109.73, 150.26], [117.85, 179.56], [157.28, 182.19], [170.68, 149.92], [168.19, 109.11], [128.98, 111.5], [121.4, 71.76], [131.12, 36.36], [91.91, 36.81], [52.16, 34.88], [14.01, 43.04], [8.27, 83.34], [5.01, 119.66], [38.87, 124.3], [51.88, 159.02]];

// Module for 2D stadium/oval
module stadium_2d(length, width) {
    hull() {
        translate([-(length - width)/2, 0])
            circle(d = width);
        translate([(length - width)/2, 0])
            circle(d = width);
    }
}

// Module for single notched oval collar (Z = 1.0 to 4.0mm)
module single_collar() {
    difference() {
        // Outer oval collar wall
        linear_extrude(height = collar_height)
            stadium_2d(collar_inner_length + 2 * collar_wall_thickness, collar_inner_width + 2 * collar_wall_thickness);
        
        // Inner 10x5mm cavity
        translate([0, 0, -0.1])
            linear_extrude(height = collar_height + 0.2)
                stadium_2d(collar_inner_length, collar_inner_width);
        
        // Wire pass-through notches on both 5mm ends down to floor
        translate([(collar_inner_length + collar_wall_thickness)/2, 0, collar_height/2])
            cube([collar_wall_thickness * 2 + 1, notch_width, collar_height + 0.2], center = true);
        
        translate([-(collar_inner_length + collar_wall_thickness)/2, 0, collar_height/2])
            cube([collar_wall_thickness * 2 + 1, notch_width, collar_height + 0.2], center = true);
    }
}

module open_chassis_tpu_armor() {
    difference() {
        union() {
            // 1. SOLID CONTINUOUS BASE PLATE (Z = 0 to 2.0mm)
            linear_extrude(height = front_thickness, convexity = 10)
                polygon(points = contour_pts);

            // 2. 4.0mm PERIMETER WALL RIM (Z = 2.0 to 6.0mm)
            translate([0, 0, front_thickness])
                linear_extrude(height = perimeter_rim_height, convexity = 10)
                    difference() {
                        polygon(points = contour_pts);
                        offset(r = -rim_wall_thickness)
                            polygon(points = contour_pts);
                    }

            // 3. 16 OUTSIDE PERIMETER FASTENER TABS (Flush with Backside Z = 6.0mm, Pure Round)
            for (i = [0 : len(fastener_tabs)-1]) {
                translate([fastener_tabs[i][0], fastener_tabs[i][1], 4.0])
                    difference() {
                        // Pure round cylinder from Z = 4.0 to 6.0mm
                        cylinder(d = fastener_tab_od, h = fastener_tab_thick);
                        // Through-hole
                        translate([0, 0, -0.2])
                            cylinder(d = fastener_hole_dia, h = fastener_tab_thick + 0.4);
                    }
            }

            // 4. 100 NOTCHED OVAL COLLARS (Z = 1.0 to 4.0mm)
            for (i = [0 : len(ordered_leds)-1]) {
                translate([ordered_leds[i][0], ordered_leds[i][1], pocket_floor_z])
                    rotate([0, 0, led_rotations[i]])
                        single_collar();
            }
        }

        // 5. 1.0mm RECESS CUTTERS IN FLOOR UNDER POCKETS (Z = 1.0 to 2.1mm)
        for (i = [0 : len(ordered_leds)-1]) {
            translate([ordered_leds[i][0], ordered_leds[i][1], pocket_floor_z])
                rotate([0, 0, led_rotations[i]])
                    linear_extrude(height = front_thickness - pocket_floor_z + 0.1)
                        stadium_2d(collar_inner_length, collar_inner_width);
        }

        // 6. 2x2mm SQUARE OPTICAL WINDOWS (Through front plate Z = -0.5 to 1.5mm)
        for (i = [0 : len(ordered_leds)-1]) {
            translate([ordered_leds[i][0], ordered_leds[i][1], -0.2])
                rotate([0, 0, led_rotations[i]])
                    linear_extrude(height = pocket_floor_z + 0.4)
                        square([window_square, window_square], center = true);
        }

        // 7. DEBOSSED LED NUMBERS 1-100 ON INNER FLOOR (Z = 1.4 to 2.1mm)
        for (i = [0 : len(number_positions)-1]) {
            translate([number_positions[i][0], number_positions[i][1], front_thickness - 0.6])
                linear_extrude(height = 0.8)
                    mirror([1, 0, 0])
                        text(str(i + 1), size = 2.8, valign = "center", halign = "center", font = "Liberation Sans:style=Bold");
        }
    }
}

open_chassis_tpu_armor();
